version: '3.8'

services:
  database:
    image: postgres:alpine
    env_file: .env
    ports:
      - '5432:5432'

  storefront:
    build: 
      context: .
      dockerfile: apps/storefront/Dockerfile
    ports:
      - '3000:80'

  dashboard:
    build: 
      context: .
      dockerfile: apps/dashboard/Dockerfile
    ports:
      - '3001:80'
