export const enum ShippingMethod {
  INSTANT_TELEPORTATION = 'INSTANT_TELEPORTATION',
  DRONE = 'DRONE',
  SELF_DRIVING_TRUCK = 'SELF_DRIVING_TRUCK',
  HYPERLOOP = 'HYPERLOOP',
}

export const enum PaymentMethod {
  BIOMETRIC = 'BIOMETRIC',
  CRYPTO = 'CRYPTO',
  VIRTUAL_WALLET = 'VIRTUAL_WALLET',
  SMART_CONTRACT = 'SMART_CONTRACT',
  CREDIT_CARD = 'CREDIT_CARD',
}
