apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail.name" . }}
type: Opaque
data:
  MAIL_USERNAME: {{ .Values.mail.username | b64enc }}
  MAIL_PASSWORD: {{ .Values.mail.password | b64enc }}
