name: Reusable action for publishing docker images using Docker directly
description: Composes Docker actions in order to publish an artifact

inputs:
  dockerfile:
    description: The dockerfile to build
    required: true

  container-name:
    description: The name of the container
    required: true

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: |
          ghcr.io/thedatasnok/${{ inputs.container-name }}:latest
          ghcr.io/thedatasnok/${{ inputs.container-name }}:${{ github.ref_name }}
