name: Reusable action for publishing docker images using Docker directly
description: Composes Docker actions in order to publish an artifact

inputs:
  selector:
    description: The selector for targeting which subproject to run the jib task against
    required: true

  registry-username:
    description: The username to use to authenticate with the container registry
    required: true

  registry-password:
    description: The password to use to authenticate with the container registry
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Run jib publish
      shell: bash
      run: ./gradlew ${{ inputs.selector }}:jib
