apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.name" . }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "backend.name" .) ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $accessTokenSecret := (get $secretData "ACCESS_TOKEN_SECRET") | default (randAlphaNum 48 | b64enc) }}
  {{- $refreshTokenSecret := (get $secretData "REFRESH_TOKEN_SECRET") | default (randAlphaNum 48 | b64enc) }}
  ACCESS_TOKEN_SECRET: {{ $accessTokenSecret | quote }}
  REFRESH_TOKEN_SECRET: {{ $refreshTokenSecret | quote }}
  S3_ACCESS_KEY: {{ .Values.s3.accessKey | b64enc }}
  S3_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc }}
