apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  labels:
    {{ include "chart.labels" . }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      rewrite ^/admin/(.*)$ /$1 break;
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "storefront.name" . }}
                port:
                  number: {{ include "storefront.port" . }}

          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ include "dashboard.name" . }}
                port:
                  number: {{ include "dashboard.port" . }}

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "bot.name" . }}
                port:
                  number: {{ include "bot.port" . }}

  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: "{{ .Chart.Name }}-tls"